### ISSUE TITLE
Add data source query parameter to field mapping

### ISSUE THREAD

**Issue by jessestewart1** [goatsweater/nrn-rrn#40]
**Is your feature request related to a problem? Please describe.**
Some data sources have data destined for multiple nrn datasets combined into the same file / layer. Example: NB maintenance dataset is a file gdb with both ferries and roads.

**Describe the solution you'd like**
Add query capabilities to separate data in the same file / layer, including an optional key added to the `data` key in the field mapping yaml to specify a query.
YAML current:
```
data:
  filename: NBRN_Export.gdb
  layer: Road_Segment_Entity
  driver: OpenFileGDB
  crs: "EPSG:2953"
  spatial: True
```
YAML proposed (with example query to extract ferries):
```
data:
  filename: NBRN_Export.gdb
  layer: Road_Segment_Entity
  driver: OpenFileGDB
  crs: "EPSG:2953"
  spatial: True
  query: "\"FUNCTIONAL_ROAD_CLASS\" = 425"
```
